language: python

# Makes Travis skip looking for requirements.txt
install: pip --version

before_script:
  - rm -rf export/markdown/* export/full-json/* export/html/*
  #- ls -alh
  - cd export

script:
  - ../scripts/download-project-files.py

after_script:
  - ls -alh markdown/
  - git status
