language: python

# Makes Travis skip looking for requirements.txt
install: pip --version

before_script:
  #- ls -alh
  - rm -rf export/markdown/core*.md export/full-json/* export/html/*
  - cd export

script:
  - ../scripts/download-project-files.py

after_script:
  #- ls -alh markdown/
  - git checkout -b backup
  - git status
  - git remote -v
  - git push origin HEAD:backup
  - git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
